name: Add voices.zip to created release

on:
    workflow_call:

jobs:
    convert-voices:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install torch --index-url https://download.pytorch.org/whl/cpu
                  pip install requests numpy bs4

            - name: Collect Kokoro voices from HuggingFace and Convert to .npy
              run: |
                  mkdir -p voices
                  python ./convert_kokoro_voices.py

            - name: Zip and upload to release
              run: |
                  curl -o LICENSE https://www.apache.org/licenses/LICENSE-2.0.txt
                  zip -r voices.zip voices
                  gh release upload ${{ github.ref_name }} voices.zip --clobber
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              shell: bash
