name: Create Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Create GitHub Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release create ${GITHUB_REF#refs/tags/} \
                    --title "Release ${GITHUB_REF#refs/tags/}" \
                    --notes "Automated release of binaries needed by KokoroSharp's `.nupkg`."
