name: Create Release

on:
    push:
        tags:
            - "*"

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Create GitHub Release
              run: |
                  gh release create ${{ github.ref_name }} \
                    --title "Release ${{ github.ref_name }}" \
                    --notes "Automated release of binaries needed by KokoroSharp's `.nupkg`."
