name: Create Release

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    create-release:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Create GitHub Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release create ${GITHUB_REF#refs/tags/} \
                    --title "Release ${GITHUB_REF#refs/tags/}" \
                    --notes "Automated release of binaries needed by KokoroSharp's \`.nupkg\`."

    build-espeak:
        needs: create-release
        uses: ./.github/workflows/build-espeak.yml
        with:
            matrix: |
                [
                  { "platform": "macos-14", "bin": "espeak-ng-macos-arm64.dll" },
                  { "platform": "macos-13", "bin": "espeak-ng-macos-amd64.dll" },
                  { "platform": "ubuntu-20.04", "bin": "espeak-ng-linux-amd64.dll" },
                  { "platform": "windows-latest", "bin": "espeak-ng-win-amd64.dll" },
                  { "platform": "windows-latest", "bin": "espeak-ng-win-arm64.dll", "extra-cmake-args": "-A ARM64" }
                ]
